import { useEffect, useCallback, useMemo } from 'react';
import { Info, Plus, Trash2, GripVertical, ChevronDown } from 'lucide-react';
import { cn } from '../../../../utils/cn';
import type { WizardFormData } from '../../../../hooks/useSkillWizard';
import type { InputSchemaField } from '../../../../types/skills';

interface InputFieldsStepProps {
  formData: WizardFormData;
  errors: Record<string, string>;
  onUpdateInputSchema: (schema: InputSchemaField[]) => void;
  onValidate: (valid: boolean) => void;
}

const FIELD_TYPES: { value: InputSchemaField['type']; label: string; description: string }[] = [
  { value: 'string', label: 'Text', description: 'Single line text input' },
  { value: 'number', label: 'Number', description: 'Numeric input' },
  { value: 'boolean', label: 'Toggle', description: 'Yes/No switch' },
  { value: 'array', label: 'List', description: 'Comma-separated values' },
  { value: 'object', label: 'JSON', description: 'JSON object input' },
];

export function InputFieldsStep({
  formData,
  errors,
  onUpdateInputSchema,
  onValidate,
}: InputFieldsStepProps) {
  // Extract variables from user prompt template
  const extractedVariables = useMemo(() => {
    const template = formData.userPromptTemplate || '';
    const matches = template.match(/\{\{([^}]+)\}\}/g) || [];
    return [...new Set(matches.map(m => m.replace(/\{\{|\}\}/g, '').trim()))];
  }, [formData.userPromptTemplate]);

  // Auto-generate input schema from extracted variables
  useEffect(() => {
    if (extractedVariables.length > 0 && formData.inputSchema.length === 0) {
      const autoGeneratedSchema: InputSchemaField[] = extractedVariables.map((name) => ({
        name,
        type: 'string',
        description: '',
        required: true,
      }));
      onUpdateInputSchema(autoGeneratedSchema);
    }
  }, [extractedVariables, formData.inputSchema.length, onUpdateInputSchema]);

  // Validate step - input fields are optional
  const validateStep = useCallback(() => {
    // Check that all fields have valid names
    const allFieldsValid = formData.inputSchema.every(
      (field) => field.name.trim().length > 0
    );
    onValidate(allFieldsValid);
  }, [formData.inputSchema, onValidate]);

  useEffect(() => {
    validateStep();
  }, [validateStep]);

  const addField = () => {
    const newField: InputSchemaField = {
      name: `field_${formData.inputSchema.length + 1}`,
      type: 'string',
      description: '',
      required: false,
    };
    onUpdateInputSchema([...formData.inputSchema, newField]);
  };

  const removeField = (index: number) => {
    const newSchema = formData.inputSchema.filter((_, i) => i !== index);
    onUpdateInputSchema(newSchema);
  };

  const updateField = (index: number, updates: Partial<InputSchemaField>) => {
    const newSchema = formData.inputSchema.map((field, i) =>
      i === index ? { ...field, ...updates } : field
    );
    onUpdateInputSchema(newSchema);
  };

  const moveField = (fromIndex: number, toIndex: number) => {
    if (toIndex < 0 || toIndex >= formData.inputSchema.length) return;
    const newSchema = [...formData.inputSchema];
    const [removed] = newSchema.splice(fromIndex, 1);
    newSchema.splice(toIndex, 0, removed);
    onUpdateInputSchema(newSchema);
  };

  return (
    <div className="space-y-6">
      {/* Step Description */}
      <div className="flex items-start gap-3 p-4 bg-primary/5 border border-primary/20 rounded-lg">
        <Info size={20} className="text-primary mt-0.5" />
        <div>
          <h3 className="font-medium text-foreground mb-1">Input Fields</h3>
          <p className="text-sm text-muted-foreground">
            Define the input fields users will fill in when running this skill.
            Fields are auto-generated from your prompt template variables.
          </p>
        </div>
      </div>

      {/* Detected Variables Info */}
      {extractedVariables.length > 0 && (
        <div className="p-3 bg-muted/30 border border-border rounded-lg">
          <p className="text-sm text-muted-foreground">
            <span className="font-medium text-foreground">{extractedVariables.length}</span> variable(s)
            detected from your prompt: {extractedVariables.map(v => (
              <code key={v} className="mx-1 px-1 py-0.5 bg-primary/10 text-primary text-xs rounded">
                {`{{${v}}}`}
              </code>
            ))}
          </p>
        </div>
      )}

      {/* Input Fields List */}
      <div className="space-y-4">
        {formData.inputSchema.map((field, index) => (
          <div
            key={index}
            className="p-4 bg-card border border-border rounded-lg"
          >
            <div className="flex items-start gap-3">
              {/* Drag Handle */}
              <button
                type="button"
                className="mt-2 p-1 text-muted-foreground hover:text-foreground cursor-grab"
                onMouseDown={() => {}}
              >
                <GripVertical size={16} />
              </button>

              {/* Field Configuration */}
              <div className="flex-1 space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  {/* Field Name */}
                  <div>
                    <label className="block text-xs font-medium text-muted-foreground mb-1">
                      Field Name
                    </label>
                    <input
                      type="text"
                      value={field.name}
                      onChange={(e) => updateField(index, { name: e.target.value })}
                      placeholder="field_name"
                      className={cn(
                        'w-full px-3 py-2 bg-muted/50 border border-border rounded-lg text-sm',
                        'focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/50',
                        'font-mono'
                      )}
                    />
                  </div>

                  {/* Field Type */}
                  <div>
                    <label className="block text-xs font-medium text-muted-foreground mb-1">
                      Field Type
                    </label>
                    <div className="relative">
                      <select
                        value={field.type}
                        onChange={(e) => updateField(index, { type: e.target.value as InputSchemaField['type'] })}
                        className={cn(
                          'w-full px-3 py-2 pr-8 bg-muted/50 border border-border rounded-lg text-sm',
                          'focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/50',
                          'appearance-none cursor-pointer'
                        )}
                      >
                        {FIELD_TYPES.map((type) => (
                          <option key={type.value} value={type.value} className="bg-card">
                            {type.label}
                          </option>
                        ))}
                      </select>
                      <ChevronDown
                        size={14}
                        className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground pointer-events-none"
                      />
                    </div>
                  </div>
                </div>

                {/* Description */}
                <div>
                  <label className="block text-xs font-medium text-muted-foreground mb-1">
                    Description (shown to users)
                  </label>
                  <input
                    type="text"
                    value={field.description || ''}
                    onChange={(e) => updateField(index, { description: e.target.value })}
                    placeholder="Help text for this field..."
                    className={cn(
                      'w-full px-3 py-2 bg-muted/50 border border-border rounded-lg text-sm',
                      'focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/50'
                    )}
                  />
                </div>

                {/* Required Toggle */}
                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    id={`required-${index}`}
                    checked={field.required ?? false}
                    onChange={(e) => updateField(index, { required: e.target.checked })}
                    className="w-4 h-4 accent-primary rounded"
                  />
                  <label
                    htmlFor={`required-${index}`}
                    className="text-sm text-muted-foreground cursor-pointer"
                  >
                    Required field
                  </label>
                </div>
              </div>

              {/* Delete Button */}
              <button
                type="button"
                onClick={() => removeField(index)}
                className="p-2 text-muted-foreground hover:text-destructive hover:bg-destructive/10 rounded-lg transition-colors"
                aria-label="Remove field"
              >
                <Trash2 size={16} />
              </button>
            </div>

            {/* Move Buttons */}
            <div className="flex items-center gap-2 mt-3 pt-3 border-t border-border">
              <button
                type="button"
                onClick={() => moveField(index, index - 1)}
                disabled={index === 0}
                className={cn(
                  'text-xs px-2 py-1 rounded transition-colors',
                  index === 0
                    ? 'text-muted-foreground/50 cursor-not-allowed'
                    : 'text-muted-foreground hover:text-foreground hover:bg-muted'
                )}
              >
                Move Up
              </button>
              <button
                type="button"
                onClick={() => moveField(index, index + 1)}
                disabled={index === formData.inputSchema.length - 1}
                className={cn(
                  'text-xs px-2 py-1 rounded transition-colors',
                  index === formData.inputSchema.length - 1
                    ? 'text-muted-foreground/50 cursor-not-allowed'
                    : 'text-muted-foreground hover:text-foreground hover:bg-muted'
                )}
              >
                Move Down
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Add Field Button */}
      <button
        type="button"
        onClick={addField}
        className={cn(
          'w-full p-4 border-2 border-dashed border-border rounded-lg',
          'flex items-center justify-center gap-2 text-sm text-muted-foreground',
          'hover:border-primary/50 hover:text-foreground transition-colors'
        )}
      >
        <Plus size={18} />
        Add Input Field
      </button>

      {/* Empty State */}
      {formData.inputSchema.length === 0 && (
        <div className="text-center py-8">
          <p className="text-muted-foreground mb-2">No input fields defined yet.</p>
          <p className="text-sm text-muted-foreground">
            Add fields manually or they will be auto-generated from your prompt variables.
          </p>
        </div>
      )}
    </div>
  );
}
